### ISSUE TITLE
Unable to handle missing dewpoint

### ISSUE THREAD

**Issue by fralut** [SagemCassiopee/php-metar-decoder#16]
Looks like the libraray is unable to handle missing dewpoint like LSZL 131550Z AUTO 09005KT 060V120 9999NDV -SHRA SCT052 BKN067 13/// Q1008 RMK=

 Invalid format:
  -  Atmospheric pressure not found, on chunk "13/// Q1008 RMK"

Thanks for the great work !

**Comment by inouire** [comment]
Thanks for your contribution with a clear example. I'll look into it and let you know.

**Comment by fralut** [comment]
The issue was also new to me. Looks like that this was a well know issue with the "old" sensor generation. I have one case where we didn't received a dew point or 3 days.
Thanks that you will have a look on this issue.

**Comment by inouire** [comment]
Hey @fralut. Now that I looked closer at your issue, I realize that the case you're mentionning is "normal". As you know, your sample METAR does not have the expected format for the temperature chunk. In strict parsing mode this leads to a fatal error (and so does any chunk that does not follow the norm) In non-strict mode it simply makes the whole temperature chunk invalid.

If you have a look at the [non-strict decoding](https://php-metar-decoder.cassiopee.aero/index.php?metar=LSZL+131550Z+AUTO+09005KT+060V120+9999NDV+-SHRA+SCT052+BKN067+13%2F%2F%2F+Q1008+RMK%3D) you can see that the pressure information is parsed correctly, despite the error message. This is because of parsing retry mechanism in non-strict mode. More information [here](https://github.com/SagemCassiopee/php-metar-decoder#about-parsing-errors-again).

Let me know if you have any question !
